const FONTS = {
  PROXIMA_NOVA_BLACK: 'ProximaNova-Black',
  PROXIMA_NOVA_BOLD: 'ProximaNova-Bold',
  PROXIMA_NOVA_EXTRABOLD: 'ProximaNova-ExtraBold',
  PROXIMA_NOVA_MEDIUM: 'ProximaNova-SemiBold',
  PROXIMA_NOVA_LIGHT: 'ProximaNova-Light',
  PROXIMA_NOVA_REGULAR: 'ProximaNova-Regular',
  PROXIMA_NOVA_SEMI_BOLD: 'ProximaNova-SemiBold',
  PROXIMA_NOVA_THIN: 'ProximaNovaT-Thin',
  POPPINS_BLACK: 'Poppins-Black',
  POPPINS_BOLD: 'Poppins-Bold',
  POPPINS_EXTRABOLD: 'Poppins-ExtraBold',
  POPPINS_SEMIBOLD: 'Poppins-SemiBold',
  POPPINS_LIGHT: 'Poppins-Light',
  POPPINS_REGULAR: 'Poppins-Regular',
  POPPINS_THIN: 'Poppins-Thin',
  POPPINS_MEDIUM: 'Poppins-Medium',
  LATO_REGULAR: 'Lato-Regular',
  ROBOTTO_BOLD: 'Poppins-Bold',
  ROBOTTO_SEMIBOLD: 'Poppins-SemiBold',
  ROBOTTO_MEDIUM: 'Poppins-Medium',
  ROBOTTO_REGULAR: 'Poppins-Regular',
  RUBIK_MEDIUM: 'Rubik-Medium',
  RUBIK_SMALL: 'Rubik-Regular',
  // RUBIK_LARGE:'Rubik-Medium',
  RUBIK_SEMIBOLD: 'Rubik-SemiBold',
};
export default FONTS;
