const ImagePath = {
  BLUECHECKBOX: require('../Assets/Images/Bluecheck.png'),
  WHITECHECKBOX: require('../Assets/Images/whitecheck.png'),
  SUCESSJSON: require('../Assets/Lottie/sucessverification.json'),
  LOGINPAGE_BACKGROUNGD: require('../Assets/Images/loginpagebg.png'),
  USER_ICON: require('../Assets/Images/userprofile.png'),
  LOCK_ICON: require('../Assets/Images/userlock.png'),
  EYE_ICON: require('../Assets/Images/usereye.png'),
  FORGOTPASSWORD_BG: require('../Assets/Images/forgotpasssordbg.png'),
  SETNEWPASSWORD_BG: require('../Assets/Images/newpasswordbg.png'),
  VERIFYOTP_BG: '../Assets/Images/verifyotpbg.png',
  PHONE_ICON: '../Assets/Images/phoneIcon.png',
  SIGNUP: require('../Assets/Images/signup.png'),
  DASHBOARD: require('../Assets/Images/dashboard.png'),
  LOGO: require('../Assets/Images/logo.png'),
  BELL: require('../Assets/Images/bell.png'),
  SEARCH: require('../Assets/Images/search.png'),
  BBPS: require('../Assets/Images/bbps.png'),
  AROOW_FOROWARD: require('../Assets/Images/arrow_foroward.png'),
  RECHARGE: require('../Assets/Images/recharge.png'),
  BUS: require('../Assets/Images/bus.png'),
  APARTMENT: require('../Assets/Images/apartment.png'),
  FLIGHT: require('../Assets/Images/flight.png'),
  BANNER_1: require('../Assets/Images/banner_1.png'),
  BANNER_2: require('../Assets/Images/banner_2.png'),
  MENU_ICON: require('../Assets/Images/menu.png'),
  HOME: require('../Assets/Images/home.png'),
  TRANSACTIONS: require('../Assets/Images/transactions.png'),
  PROFILE: require('../Assets/Images/profile.png'),
  HISTORY: require('../Assets/Images/history.png'),
  CLOSE_ICON: require('../Assets/Images/cancel.png'),
  DTH: require('../Assets/Images/dth.png'),
  PERSON: require('../Assets/Images/person.jpg'),
  QRCODE: require('../Assets/Images/ptm_qr_code.png'),
  COPY: require('../Assets/Images/copy.png'),
  SHARE: require('../Assets/Images/share.png'),
  WHITE_ARROW:require('../Assets/Images/whitebackarrow.png'),
  BLACK_ARROW:require('../Assets/Images/blackarrow.png'),
  BBPS_HORIZONTAL:require('../Assets/Images/bbpshorizontal.png'),
  UPI_LOGOS:require('../Assets/Images/upilogo.png'),
  // WHITE_ARROW: require('../Assets/Images/whitebackarrow.png'),
  // BLACK_ARROW: require('../Assets/Images/blackarrow.png'),
  // BBPS_HORIZONTAL: require('../Assets/Images/bbpshorizontal.png'),
  TRANSACTION_BG: require('../Assets/Images/pament_bg.png'),
  TRANSACTION_MASK: require('../Assets/Images/transactions_mask.png'),
  PAYMENT_BG: require('../Assets/Images/payment_bg.png'),
  PAY_SUCCESS: require('../Assets/Lottie/Check.json'),
  PAY_PENDING: require('../Assets/Lottie/Pending.json'),
  PAY_FAILED: require('../Assets/Lottie/Cancel.json'),
  PAY_CONFETTI: require('../Assets/Lottie/confetti.json'),
  CHECK: require('../Assets/Images/check.png'),
  SHARE_TWO: require('../Assets/Images/share2.png'),
  COPY_TWO: require('../Assets/Images/copy2.png'),
  AIRTEL:require('../Assets/Images/aitel.png'),
  DISHTV:require('../Assets/Images/dishtv.png'),
  PROFILEBACKGROUND:require('../Assets/Images/profilebackground.png'),
  EDIT_ICON:require('../Assets/Images/editpencil.png'),
  BLANK_IMG:require('../Assets/Images/editpencil.png'),
  PROFILE_IMG_MAIN:require('../Assets/Images/profilemain.png'),
  BANNER_IMG1:require('../Assets/Images/bannerimg1.png'),
  BANNER_IMG2:require('../Assets/Images/bannerimg2.png'),
  BANNER_IMG3:require('../Assets/Images/bannerimg3.png'),
  BANNER_IMG4:require('../Assets/Images/bannerimg4.png'),
  BANNER_IMG5:require('../Assets/Images/bannerimg5.png'),
  BANNER_IMG6:require('../Assets/Images/bannerimg6.png'),
  BANNER_IMG8:require('../Assets/Images/bannerimg8.png'),
  BANNER_IMG9:require('../Assets/Images/bannerimg9.png'),
  HELP_SUPPORT:require('../Assets/Images/help.png'),
  PENDING_BG:require('../Assets/Images/pending_bg.png'),
  FAILED_BG:require('../Assets/Images/failed_bg.png'),
  PENDING_ICON:require('../Assets/Images/inprocessicon.png'),
  CROSS:require('../Assets/Images/failedicon.png'),
};
export default ImagePath;
